### ISSUE TITLE
sign the vouchers and membership card wit hthe new key and tz method

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/tezotopia-issuer#18]
did:tz:tz2X3K4x7346aUkER2NXSyYowG23ZRbueyse

**Comment by zvjezdantasic** [comment]
we confirmed that `tz` is not working @ThierryThevenet

**Comment by ThierryThevenet** [comment]
can you try to sign with didkit in using the verification method = did:tz:tz2X3K4x7346aUkER2NXSyYowG23ZRbueyse#blockchainAccountId

**Comment by zvjezdantasic** [comment]
so, do you want me to add the method manually not generating?

**Comment by ThierryThevenet** [comment]
Yes i am quite sure that it will work. I remember now that i talked to the guys from Spruce last year about that issue in nodejs.
. It is an issue of the function to get the verification method from the key but the signing function is ok, I guess.

**Comment by ThierryThevenet** [comment]
we give up with tz
