### ISSUE TITLE
Avoid talking associated wallet or associated address 

### ISSUE THREAD

**Issue by nicolasmullertalao** [TalaoDAO/tezotopia-issuer#3]
I think that after scanning the QR code, the user should be asked to choose, among the addresses stored his AltMe wallet, with which address he plays, instead of the message "Select your Tezos associated wallet" which is incomprehensible for a user
![IMG_0883](https://user-images.githubusercontent.com/72191863/174071715-ae5b673c-ad18-4d4c-8993-469be5bb1dbb.PNG)
r

**Comment by ThierryThevenet** [comment]
cf mobile dev
