### ISSUE TITLE
issue membership for mobile

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/tezotopia-issuer#66]
same code as membership card with a fixed url 

https://issuer.tezotopia.altme.io/issuer/membershipcard_mobile

**Comment by zvjezdantasic** [comment]
should we remove membership_xxx @ThierryThevenet ?

**Comment by zvjezdantasic** [comment]
@ThierryThevenet would you explain in detail?

**Comment by thierry-thevenet** [comment]
same approach as for the voucher mobile.
we need a membershipcard to get through the mobile only . The link is unique.
