### ISSUE TITLE
membership card standard, change browser Tab -> Tezotopia voucher

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/tezotopia-issuer#67]

**Comment by zvjezdantasic** [comment]
@ThierryThevenet would you explain in detail?

**Comment by thierry-thevenet** [comment]
see top in the browser Tab bar 
![Capture d’écran de 2022-09-01 18-36-30](https://user-images.githubusercontent.com/61424218/187967037-ec8acc2e-4b18-428f-bcd2-31383e943202.png)

**Comment by ThierryThevenet** [comment]
remove the "s" of "year"

**Comment by ThierryThevenet** [comment]
replace "Tezotopia voucher" by "Tezotopia membership card"

**Comment by zvjezdantasic** [comment]
@ThierryThevenet why is it not closed yet?
