### ISSUE TITLE
Check if date.now < expires, reject if not (delay expired) with return code 408

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/tezotopia-issuer#7]
return code is 408

**Comment by ThierryThevenet** [comment]
and display a message to says that the Time is out see christophe for that

**Comment by zvjezdantasic** [comment]
@ThierryThevenet please explain in detail
So, it is on the POST request and we need to return 408 to mobile wallet
right?

**Comment by ThierryThevenet** [comment]
yes
